# Generated by Django 3.2 on 2021-04-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddDev', '0002_alter_developer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='blog',
        ),
        migrations.AddField(
            model_name='developer',
            name='blog',
            field=models.ManyToManyField(to='AddDev.Blog'),
        ),
        migrations.RemoveField(
            model_name='developer',
            name='domain',
        ),
        migrations.AddField(
            model_name='developer',
            name='domain',
            field=models.ManyToManyField(to='AddDev.Domain'),
        ),
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ManyToManyField(to='AddDev.Project'),
        ),
        migrations.RemoveField(
            model_name='developer',
            name='q_a',
        ),
        migrations.AddField(
            model_name='developer',
            name='q_a',
            field=models.ManyToManyField(to='AddDev.Q_A'),
        ),
        migrations.RemoveField(
            model_name='developer',
            name='technology',
        ),
        migrations.AddField(
            model_name='developer',
            name='technology',
            field=models.ManyToManyField(to='AddDev.Technology'),
        ),
    ]
