# Generated by Django 3.2 on 2021-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddDev', '0003_auto_20210414_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
